apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
spec:
  selector:
    matchLabels:
      app: rolldice
  replicas: 1
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
        - name: rolldice
          image: derekmitchell399/rolldice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://$(NODE_IP):4317"
            - name: OTEL_SERVICE_NAME
              value: "rolldice"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "deployment.environment=test"
---
apiVersion: v1
kind: Service
metadata:
  name: rolldice
  labels:
    app: rolldice
spec:
  type: ClusterIP
  selector:
    app: rolldice
  ports:
    - port: 8080
      protocol: TCP
